/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "Auth": {
        "region": "ENTER REGION",
        "userPoolId": "ENTER USER POOL ID",
        "userPoolWebClientId": "ENTER USER POOL CLIENT ID",
    },
    "aws_project_region": "ENTER REGION",
    "aws_appsync_region": "ENTER REGION",
    //"aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;