/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "Auth": {
        "region": "ENTER_YOUR_REGION",
        "userPoolId": "ENTER_YOUR_USERPOOL_ID",
        "userPoolWebClientId": "ENTER_YOUR_USERPOOL_CLIENT_ID",
    },
    "aws_project_region": "ENTER_YOUR_REGION",
    "aws_appsync_region": "ENTER_YOUR_REGION",
 
};


export default awsmobile;