/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_xLOga1hiR",
        "userPoolWebClientId": "6hp0nem205p0jmkf8kfd6fbf3o",
    },
    "aws_project_region": "us-east-1",
    "aws_appsync_region": "us-east-1",
    //"aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;