/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "Auth": {
        "region": "us-east-2",
        "userPoolId": "us-east-2_HCzS9rHsZ",
        "userPoolWebClientId": "7bkk3frk43kq4bdttmd455r53p",
    },
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://hgcrmqskmzhhziru6eyquekety.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;