/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "Auth": {
        "region": "us-east-2",
        "userPoolId": "us-east-2_a5HMeVx8L",
        "userPoolWebClientId": "53uuism94rs3j62pveiia2fmib",
        'identityPoolId': "us-east-2:7fe3033d-e97f-4da1-b76d-309425a9b0b8"
    },
    "aws_project_region": "us-east-2",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;