/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "Auth": {
        "region": "us-east-2",
        "userPoolId": "us-east-2_Ffx8pDlvd",
        "userPoolWebClientId": "7kep7ut0qd15jfi1voqii62um4",
    },
    "aws_project_region": "us-east-2",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;